# Generated by Django 5.0.3 on 2024-04-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufactured_at',
            field=models.DateTimeField(auto_created=True, null=True, verbose_name='дата производства'),
        ),
    ]

